version: '2'
services:
  legalcode-app:
    image: legalcode
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://legalcode-mssql:1433;database=legalcode
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://legalcode-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://legalcode-elasticsearch:9200
    ports:
      - 8080:8080
  legalcode-mssql:
    extends:
      file: mssql.yml
      service: legalcode-mssql
  legalcode-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: legalcode-elasticsearch
